### ISSUE TITLE
 采用 pngquant 对资源进行压缩

### ISSUE THREAD

**Issue by 1982582704** [didi/booster#278] opened 2022-01-05 10:51 UTC
Please provide the following informations.

- System version win10

- Java version 1.8

- Gradle version gradle-5.4.1-all.zip

- Android Gradle plugin version  com.android.tools.build:gradle:3.5.0

- Booster version 4.3.0

- Stack traces
- Execution failed for task ':app:compressDebugResourcesWithPngquant'.
> A problem occurred starting process 'command 'E:\CODE\android\app\build\bin\pngquant.exe''

![999](https://user-images.githubusercontent.com/17525427/148206258-081e4b49-318e-41f5-ac28-7827c4ae8491.jpg)

**Comment by johnsonlee** [comment] 2022-06-13 12:12
Duplicate of #159

**Closed by johnsonlee** 2022-06-13 12:12 UTC
